global:
  domain: c-73a1a34.kyma.ondemand.com

srv:
  bindings:
    db:
      serviceInstanceName: hana
    auth:
      serviceInstanceName: xsuaa
    destination:
      serviceInstanceName: destination
  image:
    repository: diyadhansap/incidents-mgmt-srv-cicd
    tag: latest
  resources:
    limits:
      ephemeral-storage: 1G
      memory: 500M
    requests:
      ephemeral-storage: 1G
      cpu: 500m
      memory: 500M
  health:
    liveness:
      path: /
    readiness:
      path: /
hana-deployer:
  image:
    repository: diyadhansap/incidents-mgmt-hana-deployer-cicd
    tag: latest
  bindings:
    hana:
      serviceInstanceName: hana
  resources:
    limits:
      cpu: 2000m
      memory: 1G
    requests:
      cpu: 1000m
      memory: 1G
hana:
  serviceOfferingName: hana
  servicePlanName: hdi-shared
xsuaa:
  serviceOfferingName: xsuaa
  servicePlanName: application
  parameters:
    xsappname: incidents-diya
    tenant-mode: dedicated
html5-apps-repo-host:
  serviceOfferingName: html5-apps-repo
  servicePlanName: app-host
html5-apps-deployer:
  env:
    SAP_CLOUD_SERVICE: incidents
  envFrom:
    - configMapRef:
        name: "{{ .Release.Name }}-html5-apps-deployer-configmap"
  image:
    repository: diyadhansap/incidents-mgmt-html5-deployer-cicd
    tag: latest
  bindings:
    xsuaa:
      serviceInstanceName: xsuaa
    destination:
      serviceInstanceName: destination
    html5-apps-repo:
      serviceInstanceName: html5-apps-repo-host
  resources:
    limits:
      cpu: 2000m
      memory: 1G
    requests:
      cpu: 1000m
      memory: 1G
backendDestinations:
  srv-api:
    service: srv
destination:
  serviceOfferingName: destination
  servicePlanName: lite
  parameters:
    version: 1.0.0
    HTML5Runtime_enabled: true
